### ISSUE TITLE
interface_version is 1 octet, not 4

### ISSUE THREAD

**Issue by morepork** [mozes/smpp.pdu#1]
In line 764 of pdu/pdu_encoding.py, interface_version is specified to use Int4Encoder, when it is a 1 octet integer (see page 46 of the spec), so should be using Int1Encoder.

**Comment by theduderog** [comment]
Thank you for finding this.  It's fixed in fc41706e6ef594226c46a3681700e773528e21e7

**Comment by morepork** [comment]
That's great, thanks
