### ISSUE TITLE
An issue in pdu_encoding

### ISSUE THREAD

**Issue by farirat** [mozes/smpp.pdu#12]
at line 427:

``` python
    def _encodeSchemeDataAsInt(self, dataCoding):
        if dataCoding.scheme == pdu_types.DataCodingScheme.GSM_MESSAGE_CLASS:
            return self._encodeGsmMsgSchemeDataAsInt(dataCoding)
        raise ValueError("Unknown data coding scheme %s" % scheme)
```

first, scheme is not defined so this code would lead to an error; second the test at line 425:

``` python
        if dataCoding.scheme == pdu_types.DataCodingScheme.GSM_MESSAGE_CLASS:
```

should be fixed with casting values with str() to get the test working.

I didnt push a request with this correction because i didnt understand the difference between _encodeSchemeDataAsInt() method and this one (just on top of it):

``` python
    def _encodeSchemeNameAsInt(self, dataCoding):
        schemeName = str(dataCoding.scheme)
        if schemeName not in constants.data_coding_scheme_name_map:
            raise ValueError("Unknown data_coding scheme name %s" % schemeName)
        return constants.data_coding_scheme_name_map[schemeName]
```

schemeName is casted before the "if" test the right way, so is there any reason why its implemented in a different way in _encodeSchemeDataAsInt()

**Comment by theduderog** [comment]
Sorry if this is short. I'm on mobile right now. The type for dataCoding.scheme is intended to be an enum, not a string so the "if" test is checking enum equality using the enum module.

I hope this makes sense.  If not, can u give sample code or test where it fails?

**Comment by farirat** [comment]
Thank you, that make sense now.

What about the scheme variable at line 427 ?

**Comment by theduderog** [comment]
That looks like a bug.  Thanks.

**Comment by theduderog** [comment]
Fixed.  Thx.
