### ISSUE TITLE
concatenated text message is not working with Arabic languag

### ISSUE THREAD

**Issue by manojkakkar** [mozes/smpp.pdu#13]
Hi,

I tried sending long message for Arabic language (more than 160 characters) using Payload as well as default TLV (0x0424) submit modes but the message always gets delivered as split messages (i.e. it is not delivered as concatenated text message). 

I am using same setting for English language it's working fine and message get delivery as single concatenated message .

Any advise is highly appreciated. 

Regards,
Manoj

**Comment by theduderog** [comment]
Hi Manoj,

My understanding is that multi-part messages are always delivered as split messages and the SMS client reassembles them.  That's what I've noticed when sending message from an iPhone through a carrier to our SMPP endpoint.

Hope that helps.  I'll close this issue for now.  If you find something related to the library, please reopen it.
