### ISSUE TITLE
Manifest update not deployed to PyPI

### ISSUE THREAD

**Issue by kbaltrinic** [mozes/smpp.pdu#14]
I have an automated deployment system that is attempting to install smpp.pdu via easy_install from PyPI however it is failing due to a missing README.markdown file.  It appears this issue has been fixed in Issues 10 and 11 but the fix was never pushed to PyPI.  Can you please update PyPI?

**Comment by theduderog** [comment]
I just uploaded a new package to pypi, version 0.3.  Can you give it a try?
