### ISSUE TITLE
How to add optional parameters in a PDU

### ISSUE THREAD

**Issue by skytreader** [mozes/smpp.pdu#17]
Are optional parameters currently supported? I've been looking at the PDU class and it seems that the `optionalParams` field is initialized but not used for anything else. Maybe I'm looking at the wrong place?

(I'm willing to contribute if this is not yet supported but just making sure I don't reinvent anything. :) )

**Comment by theduderog** [comment]
Yes, optional parameters are supported.  For SubmitSM, for example, you can see the list here:

https://github.com/mozes/smpp.pdu/blob/master/smpp/pdu/operations.py#L120-L148

To create a PDU with an optional parameter, you can pass the optional param as a keyword argument in the same way that you pass mandatory parameters.

```
pdu = SubmitSM(9284,
    service_type='',
    source_addr_ton=AddrTon.ALPHANUMERIC,
    source_addr_npi=AddrNpi.UNKNOWN,
   ...
  user_message_reference=9999 #this is an optional parameter
)
```

**Comment by skytreader** [comment]
Great. Thanks for that pointer!
