### ISSUE TITLE
No module named pdu_encoding

### ISSUE THREAD

**Issue by kerr-huang** [mozes/smpp.pdu#18]
> > > from smpp.pdu.pdu_encoding import PDUEncoder
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named pdu_encoding

**Comment by theduderog** [comment]
How did you install it?  pip?  easy_install? git clone?

**Comment by kerr-huang** [comment]
C:\Users\Kerr>pip install smpp.pdu
Downloading/unpacking smpp.pdu
  Downloading smpp.pdu-0.3.tar.gz
  Running setup.py (path:c:\users\kerr\appdata\local\temp\pip_build_Kerr\smpp.pd
u\setup.py) egg_info for package smpp.pdu

```
file smpp\pdu.py (for module smpp.pdu) not found
```

Requirement already satisfied (use --upgrade to upgrade): enum in c:\python27\li
b\site-packages\enum-0.4.4-py2.7.egg (from smpp.pdu)
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\pytho
n27\lib\site-packages (from enum->smpp.pdu)
Installing collected packages: smpp.pdu
  Running setup.py install for smpp.pdu
    file smpp\pdu.py (for module smpp.pdu) not found

```
file smpp\pdu.py (for module smpp.pdu) not found
file smpp\pdu.py (for module smpp.pdu) not found
file smpp\pdu.py (for module smpp.pdu) not found
```

Successfully installed smpp.pdu
Cleaning up...

C:\Users\Kerr>python
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.

> > > import binascii
> > > import StringIO
> > > from smpp.pdu.pdu_encoding import PDUEncoder
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named pdu_encoding

**Comment by theduderog** [comment]
Hmm...I've never tried it on Windows.  I'm afraid I don't know what the
issue is.

**Comment by kerr-huang** [comment]
Thank Theduderog, I just modify  smpp/**init**.py as follows and it works fortunately.

#**import**('pkg_resources').declare_namespace(**name**)
**all**=['pdu']

**Comment by theduderog** [comment]
Great.  Glad you got it working.  If this will work for other platforms, I'd be happy to take a pull request
