### ISSUE TITLE
Is this project open source?

### ISSUE THREAD

**Issue by morepork** [mozes/smpp.pdu#2]
First off, this (and your twisted implementation too) are really nice projects.

As you can probably tell from my earlier bug report, I've been having a look at this, and a bit of a play around. However there is no licence file that I can see, so I wanted to find out if it was open source, and if so what licence it is under, as it'd be a nice library to use.

Thanks

**Comment by theduderog** [comment]
Sorry it took a while to see this issue.  For some reason, github did not send me an email about it even though I'm "watching" this project.

Thanks.  I'm glad you're finding it useful even with no documentation.  Yes, it's intended to be open-source.  I will get a license in there very soon.

**Comment by theduderog** [comment]
smpp.pdu is not updated to have an apache license
