### ISSUE TITLE
Support for TLV is not complete ?

### ISSUE THREAD

**Issue by prem-narain** [mozes/smpp.pdu#20]
In OptionEncoder class you did not write classes for self.options parameters for ms_validity,dpf_result,set_dpf,network_error_code,callback_num_pres_ind,callback_num_atag,its_reply_type,its_session_info,ussd_service_op in pdu_encoding.py
# T.ms_validity: MsValidityEncoder(),
# T.dpf_result: DpfResultEncoder(),
# T.set_dpf: SetDpfEncoder(),
# T.network_error_code: NetworkErrorCodeEncoder(),
# T.callback_num_pres_ind: CallbackNumPresIndEncoder(),
# T.callback_num_atag: CallbackNumAtag(),
# T.its_reply_type: ItsReplyTypeEncoder(),
# T.its_session_info: ItsSessionInfoEncoder(),
# T.ussd_service_op: UssdServiceOpEncoder(),

**Comment by theduderog** [comment]
Yeah, it's not complete.  Feel free to submit a pull request but I'm can't really support this repo anymore.
