### ISSUE TITLE
Character set support

### ISSUE THREAD

**Issue by humbled** [mozes/smpp.pdu#3]
Hi

Wondering if there is any character set conversion in the smpp.pdu library? The closest seems to be in sm_encoding.SMStringEncoder, but then that class doesn't seem to be used anywhere.
We're looking at our support of GSM 3.38 and ISO-8859-1.

Cheers
Brad

**Comment by theduderog** [comment]
Yes, the SMStringEncoder is the place for character conversion, although it's not that complete.  It does do ascii, UCS2, and ISO-8859-1 (Latin 1).  I wasn't able to find a python converter for GSM 3.38 at the time.  If you know of one, we could plug it in.
