### ISSUE TITLE
Is it normal to send enquirelinks when not bound ?

### ISSUE THREAD

**Issue by farirat** [mozes/smpp.pdu#7]
The client sends enquirelinks to the server when the sessions.state is not bound, this can be reproduced by simulating a server which delays bind_resp response, in the meanwhile, the client sends enquirelinks and the server will not respond since the client is not authentified "yet".

This can cause a lot of timeouted outbound exceptions, i think it is better to wait for the bind_resp before doing anything.

Am just wondering if this was done basied on some specification, if not, i'll consider it as a bug, fix it and pull it.

**Comment by theduderog** [comment]
I think you're right.  This seems like a bad idea and is likely on oversight on my part.  Thanks for finding and offering to fix it. :)

**Comment by farirat** [comment]
Sorry, i see it was an unrelated issue to smpp.pdu, it should be moved to smpp.twisted issues
