### ISSUE TITLE
The support for SubmitMulti is not complete

### ISSUE THREAD

**Issue by armonge** [mozes/smpp.pdu#8]
When trying to encode a SubmitMulti PDU there's a KeyError, also there seems to be no way to define the dest_address param

```
import binascii
from smpp.pdu.pdu_types import *
from smpp.pdu.operations import *
from smpp.pdu.pdu_encoding import PDUEncoder

pdu = SubmitMulti(
    service_type=None,
    esm_class=EsmClass(EsmClassMode.DEFAULT, EsmClassType.DEFAULT),
    protocol_id=0,
    priority_flag=PriorityFlag.LEVEL_0,
    schedule_delivery_time=None,
    validity_period=None,
    registered_delivery=RegisteredDelivery(RegisteredDeliveryReceipt.NO_SMSC_DELIVERY_RECEIPT_REQUESTED),
    replace_if_present_flag=ReplaceIfPresentFlag.DO_NOT_REPLACE,
    data_coding=DataCoding(DataCodingScheme.GSM_MESSAGE_CLASS, DataCodingGsmMsg(DataCodingGsmMsgCoding.DEFAULT_ALPHABET, DataCodingGsmMsgClass.CLASS_2)),
    sm_default_msg_id=None,
    source_addr_ton=AddrTon.ALPHANUMERIC,
    source_addr_npi=AddrNpi.UNKNOWN,
    source_addr='mobileway',
    dest_addr_ton=AddrTon.INTERNATIONAL,
    dest_addr_npi=AddrNpi.ISDN,
    number_of_dests=1,
    short_message = 'Hello World!',
)

binary = PDUEncoder().encode(pdu)
```

This has the following traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "smpp/pdu/pdu_encoding.py", line 865, in encode
    body = self.encodeBody(pdu)
  File "smpp/pdu/pdu_encoding.py", line 906, in encodeBody
    body += self.encodeRequiredParams(pdu.mandatoryParams, self.getRequiredParamEncoders(pdu), pdu.params)
  File "smpp/pdu/pdu_encoding.py", line 943, in encodeRequiredParams
    return string.join([encoderMap[paramName].encode(params[paramName]) for paramName in paramList], '')
KeyError: 'number_of_dests'
```

**Comment by theduderog** [comment]
The application that I wrote this library for did not need the SubmitMulti command and I didn't have time to fully implement it.  If you're willing to do it, I think it wouldn't be too much work.

**Comment by prem-narain** [comment]
When trying to encode a PDU there's a KeyError
 
import binascii
import StringIO
from smpp.pdu.pdu_encoding import PDUEncoder

hex = '0000004d00000005000000009f88f12441575342440001013136353035353531323334000101313737333535353430373' \
'000000000000000000300117468657265206973206e6f2073706f6f6e'
binary = binascii.a2b_hex(hex)
file = StringIO.StringIO(binary)
pdu = PDUEncoder().decode(file)
print("PDU: %s" % pdu)


This has the following traceback
 File "Test.py", line 3, in <module>
    from smpp.pdu.pdu_encoding import PDUEncoder
  File "/home/prem/smpp.pdu/smpp/pdu/pdu_encoding.py", line 18, in <module>
    from smpp.pdu import constants,pdu_types,operations
  File "/home/prem/smpp.pdu/smpp/pdu/pdu_types.py", line 20, in <module>
    CommandId = Enum(*constants.command_id_name_map.keys())
TypeError: __call__() takes at most 6 arguments (28 given)

**Comment by theduderog** [comment]
Closing this.  No plans for implement this myself.
